### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by Me0wzz** [coloriz/izms#1]
user_id, access_token 을 기입한 후, run.py를 실행 하였지만, requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url 이 뜹니다. 제가 user_id, access_token을 잘못 기입한건가요?

**Comment by Me0wzz** [comment]
💌 An ID of the most recent mail is None
Traceback (most recent call last):
  File "run.py", line 100, in <module>
    main()
  File "run.py", line 40, in main
    inbox = app.get_inbox()
  File "/home/root/izone-mail-shelter/izonemail/izonemail.py", line 101, in get_inbox
    'page': page
  File "/home/root/izone-mail-shelter/izonemail/izonemail.py", line 66, in _get
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url:api-url

**Comment by coloriz** [comment]
실제로 이 프로젝트를 쓰는 분이 계실 줄은 몰랐군여.. 이럴줄 알았으면 문서를 좀 이쁘게 작성햇을텐데 ㅎ

확인 결과 401 에러는 말씀하신대로 user_id 혹은 access_token이 틀렸을 때 발생합니다.
user_id의 경우 앚프메 앱 내의 설정에서 확인하실 수 있고 access_token은 wireshark나 Charles같은 걸로 앱의 통신 패킷을 뜯어보면 알 수 있습니다.

**Comment by ChoiWooYoung** [comment]
앗 저는 user_id, access_token 모두 앱 데이터 (/data/data/com.ca_smart.izonemail/shared_prefs/com.ca_smart.izonemail_preferences.xml 에 저장 되어있는줄 알고 해당 xml내의 user_id, access_token 값으로 해서 안됐던것 같네요. 감사합니다. 잘사용하겠습니다 ㅎㅎ!
