### ISSUE TITLE
400: Client Error

### ISSUE THREAD

**Issue by Mahilig** [coloriz/izms#2]
`python run.py
💌 An ID of the most recent mail is None
Traceback (most recent call last):
  File "/mnt/data/Projects/izone-mail-shelter/run.py", line 99, in <module>
    main()
  File "/mnt/data/Projects/izone-mail-shelter/run.py", line 39, in main
    inbox = app.get_inbox()
  File "/mnt/data/Projects/izone-mail-shelter/izonemail/izonemail.py", line 102, in get_inbox
    res = self._get(f'{self.__API_HOST}/v1/inbox', params={
  File "/mnt/data/Projects/izone-mail-shelter/izonemail/izonemail.py", line 70, in _get
    res.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://app-api.izone-mail.com/v1/inbox?is_star=0&is_unread=0&page=1`

Got both my user_id on the app. And app_token by requesting a file transfer.

**Comment by coloriz** [comment]
First, please make sure the JSON-key of your token is `access_token`, not `app_token`.

and if you're using an Android device, try changing `os-type` to `android` in https://github.com/coloriz/izone-mail-shelter/blob/e29621091bf6ef42854da8551d95ae884c8e901f/izonemail/settings.json#L3

If problems go on, let me know with more detailed logs, e.g. using curl or insomnia.

Try these commands with your `ACCESS_TOKEN` and `USER_ID`

### android
```shell
curl --request GET \
  --url 'https://app-api.izone-mail.com/v1/inbox?is_star=0&is_unread=0&page=1' \
  --header 'accept: application/json' \
  --header 'accept-encoding: gzip' \
  --header 'access-token: <ACCESS_TOKEN>' \
  --header 'application-language: ko' \
  --header 'application-version: 1.4.5' \
  --header 'os-type: android' \
  --header 'terms-version: 5' \
  --header 'user-id: <USER_ID>'
```

### iOS
```shell
curl --request GET \
  --url 'https://app-api.izone-mail.com/v1/inbox?is_star=0&is_unread=0&page=1' \
  --header 'accept: */*' \
  --header 'accept-encoding: gzip' \
  --header 'access-token: <ACCESS_TOKEN>' \
  --header 'application-language: ko' \
  --header 'application-version: 1.2.3' \
  --header 'os-type: iOS' \
  --header 'terms-version: 5' \
  --header 'user-id: <USER_ID>'
```

**Comment by Mahilig** [comment]
> First, please make sure the JSON-key of your token is `access_token`, not `app_token`.

My bad, its `access_token` in my `user_settings.json`, just not here.

I'm actually using a linux machine.

Never thought that this should be ran on an actual android phone.

**Comment by Mahilig** [comment]
> [izone-mail-shelter/izonemail/settings.json](https://github.com/coloriz/izone-mail-shelter/blob/e29621091bf6ef42854da8551d95ae884c8e901f/izonemail/settings.json#L3)
> 
> Line 3 in [e296210](/coloriz/izone-mail-shelter/commit/e29621091bf6ef42854da8551d95ae884c8e901f)
> 
>  "os-type": "iOS",

Ok, so I double checked this one, mine was originally set to `"os-type": "iOS",`

Changed it to android, and got a new error.

`Traceback (most recent call last):
  File "/mnt/data/Projects/izone-mail-shelter/run.py", line 99, in <module>
    main()
  File "/mnt/data/Projects/izone-mail-shelter/run.py", line 39, in main
    inbox = app.get_inbox()
  File "/mnt/data/Projects/izone-mail-shelter/izonemail/izonemail.py", line 102, in get_inbox
    res = self._get(f'{self.__API_HOST}/v1/inbox', params={
  File "/mnt/data/Projects/izone-mail-shelter/izonemail/izonemail.py", line 70, in _get
    res.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 426 Client Error: Upgrade Required for url: https://app-api.izone-mail.com/v1/inbox?is_star=0&is_unread=0&page=1`

**Comment by Mahilig** [comment]
> ### android
> ```shell
> curl --request GET \
>   --url 'https://app-api.izone-mail.com/v1/inbox?is_star=0&is_unread=0&page=1' \
>   --header 'accept: application/json' \
>   --header 'accept-encoding: gzip' \
>   --header 'access-token: <ACCESS_TOKEN>' \
>   --header 'application-language: ko' \
>   --header 'application-version: 1.4.5' \
>   --header 'os-type: android' \
>   --header 'terms-version: 5' \
>   --header 'user-id: <USER_ID>'
> ```

This one got me this result, I just copy pasted my  access-token and user-id form the `user_settings.json`

`{"error":{"data":{"id":"#B-0001-0000","code":400,"name":"AccessTokenError","message":"本アプリは複数端末でのご使用はできません。ご了承ください。"}}}%  `

Quick google translate said that this application(private mail) cannot be used on multiple devices. 
Therefore, I'll be trying to run it on my android phone.

**Comment by coloriz** [comment]
I've run a couple of tests and here's my results.

426 Client Error occurred when `terms-version` doesn't meet that server requires. (and currently it requires at least `5`)
It probably could happen other than this but this is all I know..
Which makes me wondering why the server returned 426 error. Cuz you're on the latest commit, right? This shouldn't happen..

> This one got me this result, I just copy pasted my access-token and user-id form the `user_settings.json`
> 
> `{"error":{"data":{"id":"#B-0001-0000","code":400,"name":"AccessTokenError","message":"本アプリは複数端末でのご使用はできません。ご了承ください。"}}}% `
> 
> Quick google translate said that this application(private mail) cannot be used on multiple devices.
> Therefore, I'll be trying to run it on my android phone.

Here Google did a great job but that's not the truth.
It seems the server doesn't care whether you're sending a request on a single-dedicated device or not.
I checked this several times.

400 error returned just when you provided a wrong user id or access-token.

Could you re-check your user id and access token pair?
I give you my empty test account created on **android** app as a sample.
```json
{
  "user-id": "57crzfhy4is0",
  "access-token": "klcr55c7000k82f1603oa6al"
}
```

**Comment by Mahilig** [comment]
> Here Google did a great job but that's not the truth.
> It seems the server doesn't care whether you're sending a request on a single-dedicated device or not.
> I checked this several times.

Okay, great. I can still use  my linux machine. It would be pretty much a hassle to use in on android, installing pip requirements hangs on me on termux. And I don't need to root my phone just for this.

> ```json
> {
>   "user-id": "57crzfhy4is0",
>   "access-token": "klcr55c7000k82f1603oa6al"
> }
> ```

Tried this and yes it gave me an empty account 
`{"mail_count":0,"page":1,"has_next_page":false,"unread_count":0,"star_count":0,"mails":[]}`

**Comment by Mahilig** [comment]
> 426 Client Error occurred when `terms-version` doesn't meet that server requires. (and currently it requires at least `5`)
> It probably could happen other than this but this is all I know..
> Which makes me wondering why the server returned 426 error. Cuz you're on the latest commit, right? This shouldn't happen..

Yes, I am on the latest commit. `terms-version` is at `5`.

Double checked both my `access-token` and `user-id`, they are both correct.

**Comment by Mahilig** [comment]
> ```json
> "access-token": "klcr55c7000k82f1603oa6al"
> ```

Seeing this one, I think I am putting the wrong `access-token`. Mine does not look like that in any way. I'm using the one given when migrating devices. It must be it.

Okay, read the closed thread. Found out the possible location for both `access-token` and `user-id`. The problem is I need root privileges to access them which I am not willing to do so. Hahaha. Stuck between a stone and a hard place.

Thank you for the replies so far. Great job.

**Comment by coloriz** [comment]
I was writing some "long comment" but i think you figured out anyway :)

The easiest way to get `access-token` is through capturing SSL packets.
I hope you make it.

FYI, I'm now developing GUI version of this script which do packet capturing, extracting tokens and all sorts of thing.
Expected to be launched before May..? i guess..

Good day, Mahilig.

**Comment by Mahilig** [comment]
> The easiest way to get `access-token` is through capturing SSL packets.
> I hope you make it.

That's what I'm doing now. Thank god for non root SSL packet apps.



> FYI, I'm now developing GUI version of this script which do packet capturing, extracting tokens and all sorts of thing.
> Expected to be launched before May..? i guess..

Looking forward to it!

Have good one!
