### ISSUE TITLE
access_token 질문

### ISSUE THREAD

**Issue by kys6879** [coloriz/izms#6]
안녕하세요 개발자님
만들어주신 프로젝트를 써보려 token을 찾으려 패킷을 보고있는데요
모든 패킷 데이터들이 암호화 되어있는거같은데, 초보자인 제가 찾는데 어려움이 있습니다 😥😥
access_token을 찾는 팁 이라도 있을까요?
감사합니다.

**Comment by coloriz** [comment]
TLS 통신은 end-to-end encryption이기 때문에 기존의 HTTP 패킷 캡쳐만으로는 볼 수 없습니다.
SSL/TLS 패킷을 복호화할 수 있는 프록시툴이 필요합니다.

저같은 경우는 [Charles](https://www.charlesproxy.com)라는 프로그램을 이용했습니다.

이것말고도 구글에 검색하시면 다양한 방법이 있습니다.
꼭 성공하시기 바랍니다.

**Comment by kys6879** [comment]
프록시를 쳐야하는군요. 감사합니다. :)
