### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by freetopoi** [coloriz/izms#7]
Hi,

I was downloading using your new build. As it closes after a while I decided to download using the python file.
But I received this error while downloading OSError: [Errno 22] Invalid argument: 'incoming\\강혜원\\20190125_오리 달래는 법 아는 사람?.html'

Below is the full information when the python ends
Traceback (most recent call last):
  File "izms.py", line 187, in <module>
    sys.exit(main())
  File "izms.py", line 167, in main
    mail_file.write_text(content, encoding='utf-8')
  File "C:\Python38\lib\pathlib.py", line 1251, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "C:\Python38\lib\pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Python38\lib\pathlib.py", line 1074, in _opener
    return self._accessor.open(self, flags, mode)
OSError: [Errno 22] Invalid argument: 'incoming\\강혜원\\20190125_오리 달래는 법 아는 사람?.html'

Also, I believe '?' in the name (Because of the mail title) might cause error as well

Below is my settings in the config file
{
  "mail_path": "incoming/{member_name}/{received:%Y%m%d}_{subject}.html",
  "embed_css": true,
  "css_path": "../css",
  "image_to_base64": true,
  "image_path": "img",
  "profile": {
    "user-id": "omitted",
    "access-token": "omitted",
    "os-type": "iOS",
    "terms-version": "5",
    "application-version": "1.2.3",
    "application-language": "ko"
  }
}

Thanks!

**Comment by coloriz** [comment]
As you expected, '?' in the path is the problem.
So clearly Windows NTFS file system cannot handle special characters in the path..

I'll label this issue as a bug.
Until fixed, please don't use {subject} in the `mail_path`.

**Comment by freetopoi** [comment]
I think I might've found a way to omit the special characters out. I tried downloading the mails now, and I'm not seeing any issues.
![image](https://user-images.githubusercontent.com/51031848/112732727-a7428700-8f76-11eb-80f9-18dada3d6a46.png)

I placed them above the part where you write the mail path thing
Here's the code, hope it helps
 # Code
            # Create a string for the possible special characters
            punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
            # Create string for subject for mail path
            no_punct = ""
            # To omit the words out
            for char in mail.subject:
                if char not in punc:
                    no_punct = no_punct + char

While doing this, I found some unrelated issues, do you prefer if I write them here or I open new task issue? As I don't think they have anything to do with this issue.

**Comment by coloriz** [comment]
might as well open the new one.

**Comment by freetopoi** [comment]
Alright! I'll close this issue as of now since the way I listed above works
