### ISSUE TITLE
March 12 2020 mails change the {member_name} to Japanese

### ISSUE THREAD

**Issue by freetopoi** [coloriz/izms#9]
Hi,

In my config file I have the following settings for reference
"mail_path": "incoming/{member_id}_{member_name}/{received:%Y%m%d}_{mail_id}_{subject}.html"
"application-language": "ko"

However for mails specifically sent on March 12 2020, the {member_name} turns into Japanese
![image](https://user-images.githubusercontent.com/51031848/112733062-b591a280-8f78-11eb-988b-cd628ce42069.png)
Those that does not have a Japanese name folder didn't send a mail on March 12 2020

Not sure why is this happening, but it doesn't really affect the downloads.

**Comment by coloriz** [comment]
This is weird.
Cannot reproduce this issue... Mines are normal.

Maybe it's a server-related issue.

**Comment by coloriz** [comment]
But thank you for reporting these kind of issues.

**Comment by freetopoi** [comment]
Yea, no problem. I wasn't sure if it's happening to others, good to know it's good on yours. It's not really a big issue so all good!
